package com.ua.estore.cgsWeb.models.driver.route;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Records which optimizer produced a route, and when. Useful for:
 * <ul>
 *   <li>Debugging "why is this route's order weird" — was it ORS or something else?</li>
 *   <li>A/B testing optimizers — compare routes generated by different providers.</li>
 *   <li>Re-running optimization later if the provider changes — know what to migrate.</li>
 * </ul>
 *
 * <p>{@link #geometryProvider} can differ from {@link #optimizerName} because
 * some providers (ORS) split the work: the optimization endpoint returns stop
 * ordering, then a separate directions call produces the geometry. We capture
 * both so we know which service did which job.</p>
 */
@Data
@NoArgsConstructor
public class OptimizationMetadata {

    /** Identifier for the optimizer that produced the stop order. e.g. "ors-vroom", "google-routes", "nearest-neighbor". */
    private String optimizerName;

    /** Identifier for the service that produced the route geometry. May equal optimizerName, or differ (ORS does). */
    private String geometryProvider;

    /** When the optimization was performed. May lag {@code Route.createdAt} slightly. */
    private LocalDateTime optimizedAt;

    /**
     * How long the optimization call(s) took, in milliseconds. Useful for
     * spotting "this provider is getting slow" trends in logs.
     */
    private Long elapsedMillis;

    /**
     * Optimizer-version string when available. e.g. ORS returns its engine
     * version in responses; Google returns a billing version. Stored as-is
     * for forensic value.
     */
    private String optimizerVersion;
}